"""
Seed Maharashtra district intelligence data into MongoDB.

Data sources:
  - UDISE+ district report cards (education indicators)
  - NFHS-5 district fact sheets (social, health)
  - Census 2011 (population, migration, agriculture dependence)
  - Maharashtra Economic Survey (employment, livelihood)
  - MSSDS / Mahaswayam (skills/training supply)

Run: python seed_districts.py
"""

import asyncio

import certifi
from motor.motor_asyncio import AsyncIOMotorClient

from app.core.config import settings

DISTRICTS = [
    {
        "id": "gondia",
        "name": "Gondia",
        "region": "Vidarbha",
        "grid": [9, 0],
        "population": {"total": 1322331, "youth": 330583},
        "indicators": {
            "education": {"score": 68, "dropout": 34.2, "transition": 58.1, "accessIndex": 42},
            "social": {"score": 62, "childMarriage": 28.1, "childLabour": 8.2, "adolescentVulnerability": 55},
            "employment": {"score": 58, "unemploymentRate": 12.4, "jobDemandIndex": 35},
            "skills": {"score": 65, "demandSupplyGap": 62, "curriculumAlignment": 38},
            "livelihood": {"score": 70, "migrationRate": 22.5, "agriDependence": 72},
            "health": {"score": 52, "youthHealthIndex": 48},
        },
        "evidenceChain": [
            {"factor": "High agricultural dependence (72%)", "arrow": True},
            {"factor": "Seasonal migration of families (22.5%)", "arrow": True},
            {"factor": "Education disruption for migrant children", "arrow": True},
            {"factor": "High dropout rate (34.2%)", "arrow": True},
            {"factor": "Limited skill development access", "arrow": False},
        ],
        "interventions": [
            {"domain": "Education", "action": "Seasonal hostel programme for migrant children", "priority": 88, "impact": "high", "reach": 4200, "feasibility": 72},
            {"domain": "Skills", "action": "Forest-produce & agri-tech short courses", "priority": 82, "impact": "high", "reach": 3100, "feasibility": 78},
            {"domain": "Employment", "action": "MGNREGA-linked skill certification", "priority": 75, "impact": "medium", "reach": 5500, "feasibility": 85},
            {"domain": "Livelihood", "action": "Bamboo & forest-based micro-enterprise", "priority": 70, "impact": "medium", "reach": 2800, "feasibility": 68},
        ],
    },
    {
        "id": "bhandara",
        "name": "Bhandara",
        "region": "Vidarbha",
        "grid": [8, 1],
        "population": {"total": 1200334, "youth": 300084},
        "indicators": {
            "education": {"score": 60, "dropout": 28.6, "transition": 63.4, "accessIndex": 48},
            "social": {"score": 55, "childMarriage": 24.3, "childLabour": 6.8, "adolescentVulnerability": 48},
            "employment": {"score": 55, "unemploymentRate": 10.8, "jobDemandIndex": 38},
            "skills": {"score": 58, "demandSupplyGap": 55, "curriculumAlignment": 45},
            "livelihood": {"score": 62, "migrationRate": 18.2, "agriDependence": 68},
            "health": {"score": 45, "youthHealthIndex": 55},
        },
        "evidenceChain": [
            {"factor": "Rice-paddy monoculture economy", "arrow": True},
            {"factor": "Limited industrial presence", "arrow": True},
            {"factor": "Youth out-migration to Nagpur", "arrow": True},
            {"factor": "Brain drain weakens local capacity", "arrow": False},
        ],
        "interventions": [
            {"domain": "Skills", "action": "Rice-processing & food-tech vocational modules", "priority": 80, "impact": "high", "reach": 2800, "feasibility": 82},
            {"domain": "Employment", "action": "Nagpur-corridor apprenticeship linkage", "priority": 76, "impact": "medium", "reach": 3200, "feasibility": 75},
            {"domain": "Education", "action": "Digital literacy centres in rural blocks", "priority": 72, "impact": "medium", "reach": 4000, "feasibility": 70},
        ],
    },
    {
        "id": "nagpur",
        "name": "Nagpur",
        "region": "Vidarbha",
        "grid": [8, 2],
        "population": {"total": 4653570, "youth": 1163393},
        "indicators": {
            "education": {"score": 32, "dropout": 14.5, "transition": 82.3, "accessIndex": 78},
            "social": {"score": 35, "childMarriage": 12.8, "childLabour": 3.2, "adolescentVulnerability": 28},
            "employment": {"score": 40, "unemploymentRate": 8.2, "jobDemandIndex": 68},
            "skills": {"score": 42, "demandSupplyGap": 38, "curriculumAlignment": 62},
            "livelihood": {"score": 25, "migrationRate": 8.5, "agriDependence": 22},
            "health": {"score": 30, "youthHealthIndex": 70},
        },
        "evidenceChain": [
            {"factor": "Strong urban infrastructure & IT corridor", "arrow": True},
            {"factor": "Good institutional density (IIMs, VNIT)", "arrow": True},
            {"factor": "Skills gap in emerging tech (AI, Cloud)", "arrow": True},
            {"factor": "Peri-urban youth excluded from growth", "arrow": False},
        ],
        "interventions": [
            {"domain": "Skills", "action": "AI & Cloud computing short-courses for polytechnic students", "priority": 85, "impact": "high", "reach": 8500, "feasibility": 88},
            {"domain": "Employment", "action": "IT Park apprenticeship programme", "priority": 82, "impact": "high", "reach": 6200, "feasibility": 90},
            {"domain": "Education", "action": "Peri-urban bridge schooling", "priority": 68, "impact": "medium", "reach": 3200, "feasibility": 72},
        ],
    },
    {
        "id": "wardha", "name": "Wardha", "region": "Vidarbha", "grid": [7, 3],
        "population": {"total": 1300774, "youth": 325194},
        "indicators": {
            "education": {"score": 45, "dropout": 20.1, "transition": 72.5, "accessIndex": 62},
            "social": {"score": 42, "childMarriage": 18.4, "childLabour": 5.1, "adolescentVulnerability": 38},
            "employment": {"score": 52, "unemploymentRate": 9.8, "jobDemandIndex": 42},
            "skills": {"score": 55, "demandSupplyGap": 50, "curriculumAlignment": 50},
            "livelihood": {"score": 55, "migrationRate": 15.2, "agriDependence": 58},
            "health": {"score": 38, "youthHealthIndex": 62},
        },
        "evidenceChain": [
            {"factor": "Cotton-dependent agrarian economy", "arrow": True},
            {"factor": "Price volatility drives farmer distress", "arrow": True},
            {"factor": "Youth aspirations mismatched with local opportunity", "arrow": True},
            {"factor": "Out-migration to Nagpur & Pune", "arrow": False},
        ],
        "interventions": [
            {"domain": "Skills", "action": "Textile & garment manufacturing skilling", "priority": 78, "impact": "high", "reach": 3500, "feasibility": 80},
            {"domain": "Livelihood", "action": "Cotton value-chain micro-enterprises", "priority": 74, "impact": "medium", "reach": 2800, "feasibility": 75},
            {"domain": "Education", "action": "Gandhian institutions digital upgrade", "priority": 70, "impact": "medium", "reach": 2200, "feasibility": 72},
        ],
    },
    {
        "id": "chandrapur", "name": "Chandrapur", "region": "Vidarbha", "grid": [9, 3],
        "population": {"total": 2204307, "youth": 551077},
        "indicators": {
            "education": {"score": 65, "dropout": 32.8, "transition": 59.2, "accessIndex": 44},
            "social": {"score": 60, "childMarriage": 26.5, "childLabour": 7.8, "adolescentVulnerability": 52},
            "employment": {"score": 50, "unemploymentRate": 11.2, "jobDemandIndex": 45},
            "skills": {"score": 60, "demandSupplyGap": 58, "curriculumAlignment": 42},
            "livelihood": {"score": 58, "migrationRate": 16.8, "agriDependence": 55},
            "health": {"score": 55, "youthHealthIndex": 45},
        },
        "evidenceChain": [
            {"factor": "Coal mining & thermal power economy", "arrow": True},
            {"factor": "Environmental health burden", "arrow": True},
            {"factor": "Single-industry skill concentration", "arrow": True},
            {"factor": "Green transition threatens livelihoods", "arrow": False},
        ],
        "interventions": [
            {"domain": "Skills", "action": "Green energy transition reskilling", "priority": 90, "impact": "high", "reach": 5500, "feasibility": 72},
            {"domain": "Employment", "action": "Solar installation & maintenance certification", "priority": 85, "impact": "high", "reach": 4200, "feasibility": 78},
            {"domain": "Health", "action": "Occupational health screening for mining-belt youth", "priority": 75, "impact": "medium", "reach": 3800, "feasibility": 68},
        ],
    },
    {
        "id": "gadchiroli", "name": "Gadchiroli", "region": "Vidarbha", "grid": [10, 3],
        "population": {"total": 1072942, "youth": 268236},
        "indicators": {
            "education": {"score": 82, "dropout": 45.6, "transition": 42.1, "accessIndex": 28},
            "social": {"score": 78, "childMarriage": 38.4, "childLabour": 14.2, "adolescentVulnerability": 72},
            "employment": {"score": 75, "unemploymentRate": 18.5, "jobDemandIndex": 18},
            "skills": {"score": 80, "demandSupplyGap": 78, "curriculumAlignment": 22},
            "livelihood": {"score": 85, "migrationRate": 32.5, "agriDependence": 82},
            "health": {"score": 72, "youthHealthIndex": 28},
        },
        "evidenceChain": [
            {"factor": "Extreme geographic isolation & tribal population", "arrow": True},
            {"factor": "Minimal institutional presence", "arrow": True},
            {"factor": "Left-wing extremism disrupts services", "arrow": True},
            {"factor": "Highest dropout & child labour rates in state", "arrow": True},
            {"factor": "Near-zero formal employment pipeline", "arrow": False},
        ],
        "interventions": [
            {"domain": "Education", "action": "Residential tribal ashramshala expansion", "priority": 95, "impact": "high", "reach": 6800, "feasibility": 55},
            {"domain": "Girls", "action": "Girls' secondary retention & scholarship", "priority": 92, "impact": "high", "reach": 4200, "feasibility": 62},
            {"domain": "Livelihood", "action": "Forest-rights enterprise development", "priority": 85, "impact": "high", "reach": 3500, "feasibility": 58},
            {"domain": "Health", "action": "Mobile health units for adolescents", "priority": 78, "impact": "medium", "reach": 5200, "feasibility": 52},
        ],
    },
    {"id": "yavatmal", "name": "Yavatmal", "region": "Vidarbha", "grid": [7, 4], "population": {"total": 2775457, "youth": 693864}, "indicators": {"education": {"score": 70, "dropout": 36.8, "transition": 55.2, "accessIndex": 40}, "social": {"score": 65, "childMarriage": 30.2, "childLabour": 9.5, "adolescentVulnerability": 58}, "employment": {"score": 62, "unemploymentRate": 14.2, "jobDemandIndex": 30}, "skills": {"score": 68, "demandSupplyGap": 65, "curriculumAlignment": 35}, "livelihood": {"score": 75, "migrationRate": 26.8, "agriDependence": 75}, "health": {"score": 60, "youthHealthIndex": 40}}, "evidenceChain": [{"factor": "Agrarian crisis — farmer suicide hotspot", "arrow": True}, {"factor": "Trauma & economic instability in families", "arrow": True}, {"factor": "Children drop out to support families", "arrow": True}, {"factor": "Child labour & early marriage as coping", "arrow": True}, {"factor": "Inter-generational poverty cycle", "arrow": False}], "interventions": [{"domain": "Education", "action": "Trauma-informed school retention programme", "priority": 92, "impact": "high", "reach": 8500, "feasibility": 65}, {"domain": "Girls", "action": "Girls' empowerment & anti-child-marriage intervention", "priority": 88, "impact": "high", "reach": 5200, "feasibility": 68}, {"domain": "Livelihood", "action": "Agri-diversification & non-farm skill pathways", "priority": 82, "impact": "high", "reach": 6800, "feasibility": 72}, {"domain": "Skills", "action": "Short-duration employable skill modules", "priority": 78, "impact": "medium", "reach": 4500, "feasibility": 78}]},
    {"id": "amravati", "name": "Amravati", "region": "Vidarbha", "grid": [6, 3], "population": {"total": 2888445, "youth": 722111}, "indicators": {"education": {"score": 55, "dropout": 26.4, "transition": 66.8, "accessIndex": 52}, "social": {"score": 50, "childMarriage": 22.1, "childLabour": 6.2, "adolescentVulnerability": 44}, "employment": {"score": 52, "unemploymentRate": 10.5, "jobDemandIndex": 42}, "skills": {"score": 55, "demandSupplyGap": 52, "curriculumAlignment": 48}, "livelihood": {"score": 58, "migrationRate": 16.5, "agriDependence": 62}, "health": {"score": 42, "youthHealthIndex": 58}}, "evidenceChain": [{"factor": "Cotton-soybean belt with moderate infrastructure", "arrow": True}, {"factor": "Education institutions present but quality gap", "arrow": True}, {"factor": "Youth prefer migration over local employment", "arrow": True}, {"factor": "Moderate skill-market mismatch", "arrow": False}], "interventions": [{"domain": "Skills", "action": "Industry-aligned diploma top-up modules", "priority": 78, "impact": "high", "reach": 5200, "feasibility": 82}, {"domain": "Employment", "action": "District industry apprenticeship network", "priority": 74, "impact": "medium", "reach": 4000, "feasibility": 78}, {"domain": "Education", "action": "Quality enhancement in rural schools", "priority": 70, "impact": "medium", "reach": 6500, "feasibility": 72}]},
    {"id": "akola", "name": "Akola", "region": "Vidarbha", "grid": [6, 4], "population": {"total": 1813906, "youth": 453477}, "indicators": {"education": {"score": 52, "dropout": 24.2, "transition": 68.5, "accessIndex": 55}, "social": {"score": 48, "childMarriage": 20.5, "childLabour": 5.8, "adolescentVulnerability": 42}, "employment": {"score": 50, "unemploymentRate": 10.2, "jobDemandIndex": 44}, "skills": {"score": 52, "demandSupplyGap": 48, "curriculumAlignment": 52}, "livelihood": {"score": 55, "migrationRate": 14.8, "agriDependence": 60}, "health": {"score": 40, "youthHealthIndex": 60}}, "evidenceChain": [{"factor": "Regional commercial hub for cotton trade", "arrow": True}, {"factor": "Moderate education infrastructure", "arrow": True}, {"factor": "Gap between education and employable skills", "arrow": True}, {"factor": "Under-utilisation of polytechnic capacity", "arrow": False}], "interventions": [{"domain": "Skills", "action": "Polytechnic modernisation — IoT & automation labs", "priority": 80, "impact": "high", "reach": 3800, "feasibility": 78}, {"domain": "Employment", "action": "Agro-processing industry linkage", "priority": 75, "impact": "medium", "reach": 3200, "feasibility": 80}]},
    {"id": "washim", "name": "Washim", "region": "Vidarbha", "grid": [6, 5], "population": {"total": 1197160, "youth": 299290}, "indicators": {"education": {"score": 72, "dropout": 38.2, "transition": 52.8, "accessIndex": 38}, "social": {"score": 68, "childMarriage": 32.5, "childLabour": 10.8, "adolescentVulnerability": 60}, "employment": {"score": 65, "unemploymentRate": 15.2, "jobDemandIndex": 25}, "skills": {"score": 70, "demandSupplyGap": 68, "curriculumAlignment": 32}, "livelihood": {"score": 72, "migrationRate": 24.5, "agriDependence": 74}, "health": {"score": 58, "youthHealthIndex": 42}}, "evidenceChain": [{"factor": "Smallest & least-developed Vidarbha district", "arrow": True}, {"factor": "Minimal industrial or service sector presence", "arrow": True}, {"factor": "High caste-based social vulnerability", "arrow": True}, {"factor": "Education access severely limited in rural talukas", "arrow": True}, {"factor": "Distress migration the primary livelihood strategy", "arrow": False}], "interventions": [{"domain": "Education", "action": "Mobile school units for scattered hamlets", "priority": 88, "impact": "high", "reach": 3200, "feasibility": 60}, {"domain": "Girls", "action": "Secondary school girls' hostel programme", "priority": 85, "impact": "high", "reach": 2400, "feasibility": 65}, {"domain": "Skills", "action": "Masonry, electrical & plumbing certification", "priority": 78, "impact": "medium", "reach": 2800, "feasibility": 78}]},
    {"id": "buldhana", "name": "Buldhana", "region": "Vidarbha", "grid": [5, 4], "population": {"total": 2586258, "youth": 646565}, "indicators": {"education": {"score": 62, "dropout": 30.5, "transition": 62.1, "accessIndex": 45}, "social": {"score": 58, "childMarriage": 26.8, "childLabour": 7.5, "adolescentVulnerability": 50}, "employment": {"score": 58, "unemploymentRate": 12.8, "jobDemandIndex": 32}, "skills": {"score": 62, "demandSupplyGap": 58, "curriculumAlignment": 42}, "livelihood": {"score": 65, "migrationRate": 20.2, "agriDependence": 68}, "health": {"score": 48, "youthHealthIndex": 52}}, "evidenceChain": [{"factor": "Drought-prone agrarian economy", "arrow": True}, {"factor": "Recurrent crop failure pushes seasonal migration", "arrow": True}, {"factor": "Education disrupted for migrant families", "arrow": True}, {"factor": "Limited non-farm employment pathways", "arrow": False}], "interventions": [{"domain": "Education", "action": "Migration-season bridge education programme", "priority": 84, "impact": "high", "reach": 5500, "feasibility": 70}, {"domain": "Skills", "action": "Solar pump & drip-irrigation technician training", "priority": 80, "impact": "high", "reach": 3800, "feasibility": 76}, {"domain": "Livelihood", "action": "Horticulture-based livelihood diversification", "priority": 75, "impact": "medium", "reach": 4200, "feasibility": 72}]},
    # -- Marathwada --
    {"id": "aurangabad", "name": "Chhatrapati Sambhajinagar", "region": "Marathwada", "grid": [4, 5], "population": {"total": 3701282, "youth": 925321}, "indicators": {"education": {"score": 38, "dropout": 16.8, "transition": 78.2, "accessIndex": 72}, "social": {"score": 38, "childMarriage": 15.2, "childLabour": 4.1, "adolescentVulnerability": 32}, "employment": {"score": 42, "unemploymentRate": 8.8, "jobDemandIndex": 62}, "skills": {"score": 45, "demandSupplyGap": 42, "curriculumAlignment": 58}, "livelihood": {"score": 30, "migrationRate": 10.2, "agriDependence": 35}, "health": {"score": 32, "youthHealthIndex": 68}}, "evidenceChain": [{"factor": "Marathwada's industrial & education hub (auto cluster)", "arrow": True}, {"factor": "Good institutional base (Dr. BAMU, polytechnics)", "arrow": True}, {"factor": "Skills gap in advanced manufacturing & IT", "arrow": True}, {"factor": "Peri-urban slum youth face exclusion", "arrow": False}], "interventions": [{"domain": "Skills", "action": "Advanced manufacturing & CNC training", "priority": 84, "impact": "high", "reach": 7500, "feasibility": 88}, {"domain": "Employment", "action": "Auto-cluster apprenticeship programme", "priority": 82, "impact": "high", "reach": 5800, "feasibility": 90}, {"domain": "Education", "action": "Slum-youth bridge-to-polytechnic pathway", "priority": 72, "impact": "medium", "reach": 4200, "feasibility": 72}]},
    {"id": "jalna", "name": "Jalna", "region": "Marathwada", "grid": [5, 5], "population": {"total": 1959046, "youth": 489762}, "indicators": {"education": {"score": 65, "dropout": 32.5, "transition": 58.8, "accessIndex": 42}, "social": {"score": 62, "childMarriage": 28.8, "childLabour": 8.8, "adolescentVulnerability": 54}, "employment": {"score": 60, "unemploymentRate": 13.5, "jobDemandIndex": 32}, "skills": {"score": 65, "demandSupplyGap": 62, "curriculumAlignment": 38}, "livelihood": {"score": 68, "migrationRate": 22.8, "agriDependence": 70}, "health": {"score": 52, "youthHealthIndex": 48}}, "evidenceChain": [{"factor": "Steel & engineering MSME cluster exists", "arrow": True}, {"factor": "But workforce lacks certified technical skills", "arrow": True}, {"factor": "Rural dropout feeds into informal child labour", "arrow": True}, {"factor": "High child marriage in tribal pockets", "arrow": False}], "interventions": [{"domain": "Skills", "action": "Welding, fabrication & quality control certification", "priority": 85, "impact": "high", "reach": 4500, "feasibility": 82}, {"domain": "Girls", "action": "Conditional cash transfer for girls' retention", "priority": 82, "impact": "high", "reach": 3800, "feasibility": 75}, {"domain": "Education", "action": "Child-labour-to-school transition programme", "priority": 78, "impact": "medium", "reach": 2800, "feasibility": 68}]},
    {"id": "beed", "name": "Beed", "region": "Marathwada", "grid": [4, 6], "population": {"total": 2585962, "youth": 646491}, "indicators": {"education": {"score": 78, "dropout": 42.5, "transition": 48.2, "accessIndex": 32}, "social": {"score": 75, "childMarriage": 35.8, "childLabour": 12.5, "adolescentVulnerability": 68}, "employment": {"score": 68, "unemploymentRate": 16.8, "jobDemandIndex": 22}, "skills": {"score": 72, "demandSupplyGap": 70, "curriculumAlignment": 30}, "livelihood": {"score": 88, "migrationRate": 42.5, "agriDependence": 78}, "health": {"score": 62, "youthHealthIndex": 38}}, "evidenceChain": [{"factor": "Sugarcane-cutting migration capital of Maharashtra", "arrow": True}, {"factor": "~500,000 seasonal migrants annually", "arrow": True}, {"factor": "Entire families migrate Oct–Mar", "arrow": True}, {"factor": "Children lose 6 months of schooling each year", "arrow": True}, {"factor": "Highest child labour & dropout in Marathwada", "arrow": False}], "interventions": [{"domain": "Education", "action": "Migration-resilient seasonal schooling (sakhar shala)", "priority": 95, "impact": "high", "reach": 12000, "feasibility": 62}, {"domain": "Girls", "action": "Secondary retention & anti-trafficking intervention", "priority": 92, "impact": "high", "reach": 5800, "feasibility": 65}, {"domain": "Skills", "action": "Off-season employable skill bootcamps", "priority": 85, "impact": "high", "reach": 8500, "feasibility": 72}, {"domain": "Livelihood", "action": "Irrigation-linked livelihood diversification", "priority": 80, "impact": "high", "reach": 6200, "feasibility": 58}]},
    {"id": "latur", "name": "Latur", "region": "Marathwada", "grid": [5, 7], "population": {"total": 2455543, "youth": 613886}, "indicators": {"education": {"score": 42, "dropout": 18.5, "transition": 76.2, "accessIndex": 68}, "social": {"score": 45, "childMarriage": 19.2, "childLabour": 5.2, "adolescentVulnerability": 38}, "employment": {"score": 55, "unemploymentRate": 11.5, "jobDemandIndex": 38}, "skills": {"score": 52, "demandSupplyGap": 48, "curriculumAlignment": 52}, "livelihood": {"score": 50, "migrationRate": 14.5, "agriDependence": 55}, "health": {"score": 38, "youthHealthIndex": 62}}, "evidenceChain": [{"factor": "Strong education culture (coaching hub)", "arrow": True}, {"factor": "But focus on competitive exams, not skills", "arrow": True}, {"factor": "Graduates unemployable in local market", "arrow": True}, {"factor": "Water scarcity limits agri-livelihood", "arrow": False}], "interventions": [{"domain": "Skills", "action": "Coaching-to-employability bridge programme", "priority": 80, "impact": "high", "reach": 6500, "feasibility": 82}, {"domain": "Employment", "action": "Service-sector job fair & placement linkage", "priority": 76, "impact": "medium", "reach": 4800, "feasibility": 85}, {"domain": "Livelihood", "action": "Water-efficient agri-enterprise training", "priority": 72, "impact": "medium", "reach": 3500, "feasibility": 70}]},
    {"id": "osmanabad", "name": "Dharashiv", "region": "Marathwada", "grid": [4, 7], "population": {"total": 1660311, "youth": 415078}, "indicators": {"education": {"score": 68, "dropout": 34.8, "transition": 56.5, "accessIndex": 40}, "social": {"score": 65, "childMarriage": 30.2, "childLabour": 9.2, "adolescentVulnerability": 56}, "employment": {"score": 62, "unemploymentRate": 14.5, "jobDemandIndex": 28}, "skills": {"score": 68, "demandSupplyGap": 65, "curriculumAlignment": 35}, "livelihood": {"score": 72, "migrationRate": 25.8, "agriDependence": 72}, "health": {"score": 55, "youthHealthIndex": 45}}, "evidenceChain": [{"factor": "Drought-prone with limited irrigation", "arrow": True}, {"factor": "Agricultural income highly volatile", "arrow": True}, {"factor": "Migration to sugarcane belts & urban areas", "arrow": True}, {"factor": "Social indicators among worst in Marathwada", "arrow": False}], "interventions": [{"domain": "Education", "action": "Drought-period education continuity programme", "priority": 86, "impact": "high", "reach": 4500, "feasibility": 65}, {"domain": "Girls", "action": "Girls' empowerment & retention scholarships", "priority": 82, "impact": "high", "reach": 3200, "feasibility": 70}, {"domain": "Skills", "action": "Masonry & construction skill certification", "priority": 76, "impact": "medium", "reach": 3800, "feasibility": 78}]},
    {"id": "nanded", "name": "Nanded", "region": "Marathwada", "grid": [6, 6], "population": {"total": 3361292, "youth": 840323}, "indicators": {"education": {"score": 62, "dropout": 30.2, "transition": 62.5, "accessIndex": 45}, "social": {"score": 58, "childMarriage": 26.5, "childLabour": 7.8, "adolescentVulnerability": 50}, "employment": {"score": 58, "unemploymentRate": 12.8, "jobDemandIndex": 35}, "skills": {"score": 60, "demandSupplyGap": 58, "curriculumAlignment": 42}, "livelihood": {"score": 62, "migrationRate": 18.5, "agriDependence": 65}, "health": {"score": 48, "youthHealthIndex": 52}}, "evidenceChain": [{"factor": "Border district with Telangana — cross-state labour flows", "arrow": True}, {"factor": "Religious tourism economy (Nanded Sahib)", "arrow": True}, {"factor": "Limited industrial diversification", "arrow": True}, {"factor": "Educated unemployment a growing concern", "arrow": False}], "interventions": [{"domain": "Skills", "action": "Hospitality & tourism skilling (pilgrimage economy)", "priority": 82, "impact": "high", "reach": 5200, "feasibility": 80}, {"domain": "Employment", "action": "Cross-border employment corridor programme", "priority": 76, "impact": "medium", "reach": 4500, "feasibility": 72}, {"domain": "Education", "action": "Rural secondary school quality improvement", "priority": 72, "impact": "medium", "reach": 6200, "feasibility": 68}]},
    {"id": "hingoli", "name": "Hingoli", "region": "Marathwada", "grid": [6, 5], "population": {"total": 1178973, "youth": 294743}, "indicators": {"education": {"score": 72, "dropout": 38.5, "transition": 52.2, "accessIndex": 35}, "social": {"score": 70, "childMarriage": 34.2, "childLabour": 11.5, "adolescentVulnerability": 62}, "employment": {"score": 68, "unemploymentRate": 16.2, "jobDemandIndex": 22}, "skills": {"score": 72, "demandSupplyGap": 70, "curriculumAlignment": 30}, "livelihood": {"score": 74, "migrationRate": 26.2, "agriDependence": 76}, "health": {"score": 60, "youthHealthIndex": 40}}, "evidenceChain": [{"factor": "Smallest Marathwada district — lowest development indices", "arrow": True}, {"factor": "Virtually no non-farm employment", "arrow": True}, {"factor": "High social vulnerability (tribal, SC communities)", "arrow": True}, {"factor": "Youth trapped in subsistence agriculture", "arrow": False}], "interventions": [{"domain": "Education", "action": "Residential bridge schools for out-of-school youth", "priority": 90, "impact": "high", "reach": 3200, "feasibility": 62}, {"domain": "Girls", "action": "Community-based anti-child-marriage programme", "priority": 86, "impact": "high", "reach": 2800, "feasibility": 65}, {"domain": "Skills", "action": "Basic digital & financial literacy", "priority": 80, "impact": "medium", "reach": 3500, "feasibility": 75}]},
    {"id": "parbhani", "name": "Parbhani", "region": "Marathwada", "grid": [5, 6], "population": {"total": 1836086, "youth": 459022}, "indicators": {"education": {"score": 65, "dropout": 32.2, "transition": 60.5, "accessIndex": 42}, "social": {"score": 60, "childMarriage": 28.5, "childLabour": 8.5, "adolescentVulnerability": 52}, "employment": {"score": 60, "unemploymentRate": 13.8, "jobDemandIndex": 30}, "skills": {"score": 65, "demandSupplyGap": 62, "curriculumAlignment": 38}, "livelihood": {"score": 68, "migrationRate": 22.2, "agriDependence": 70}, "health": {"score": 52, "youthHealthIndex": 48}}, "evidenceChain": [{"factor": "Agriculture university present but disconnect with local youth", "arrow": True}, {"factor": "Drought vulnerability & crop failure cycles", "arrow": True}, {"factor": "Migration to sugar factories & construction sites", "arrow": True}, {"factor": "Social indicators lagging despite institutional presence", "arrow": False}], "interventions": [{"domain": "Skills", "action": "Agri-university-linked practical skill modules", "priority": 82, "impact": "high", "reach": 4200, "feasibility": 80}, {"domain": "Education", "action": "Drought-resilient school attendance programme", "priority": 78, "impact": "high", "reach": 5500, "feasibility": 68}, {"domain": "Employment", "action": "MSME cluster development & youth employment", "priority": 74, "impact": "medium", "reach": 3800, "feasibility": 72}]},
    # -- Western Maharashtra --
    {"id": "pune", "name": "Pune", "region": "Western Maharashtra", "grid": [2, 6], "population": {"total": 9429408, "youth": 2357352}, "indicators": {"education": {"score": 18, "dropout": 8.2, "transition": 92.5, "accessIndex": 92}, "social": {"score": 15, "childMarriage": 5.8, "childLabour": 1.2, "adolescentVulnerability": 12}, "employment": {"score": 28, "unemploymentRate": 5.2, "jobDemandIndex": 92}, "skills": {"score": 35, "demandSupplyGap": 32, "curriculumAlignment": 68}, "livelihood": {"score": 12, "migrationRate": 4.2, "agriDependence": 12}, "health": {"score": 15, "youthHealthIndex": 85}}, "evidenceChain": [{"factor": "India's top education & IT destination", "arrow": True}, {"factor": "Strong industry-academia linkages", "arrow": True}, {"factor": "Skills gap in cutting-edge domains (AI/ML, cybersecurity)", "arrow": True}, {"factor": "Inequality: migrant slum youth excluded from tech boom", "arrow": False}], "interventions": [{"domain": "Skills", "action": "AI, Cybersecurity & Cloud certification for polytechnics", "priority": 88, "impact": "high", "reach": 15000, "feasibility": 95}, {"domain": "Employment", "action": "IT corridor internship-to-hire pipeline", "priority": 85, "impact": "high", "reach": 12000, "feasibility": 92}, {"domain": "Education", "action": "Migrant-youth urban integration programme", "priority": 72, "impact": "medium", "reach": 8500, "feasibility": 70}]},
    {"id": "satara", "name": "Satara", "region": "Western Maharashtra", "grid": [2, 7], "population": {"total": 3003741, "youth": 750935}, "indicators": {"education": {"score": 35, "dropout": 15.2, "transition": 78.8, "accessIndex": 72}, "social": {"score": 30, "childMarriage": 12.5, "childLabour": 3.5, "adolescentVulnerability": 25}, "employment": {"score": 45, "unemploymentRate": 9.2, "jobDemandIndex": 48}, "skills": {"score": 48, "demandSupplyGap": 45, "curriculumAlignment": 55}, "livelihood": {"score": 40, "migrationRate": 12.8, "agriDependence": 48}, "health": {"score": 28, "youthHealthIndex": 72}}, "evidenceChain": [{"factor": "Strong cooperative & sugar economy", "arrow": True}, {"factor": "Good basic education infrastructure", "arrow": True}, {"factor": "Youth migration to Pune for higher education & jobs", "arrow": True}, {"factor": "Local opportunities insufficient for graduates", "arrow": False}], "interventions": [{"domain": "Skills", "action": "Agri-tech & food-processing vocational modules", "priority": 78, "impact": "high", "reach": 5800, "feasibility": 82}, {"domain": "Employment", "action": "Cooperative-sector youth employment linkage", "priority": 74, "impact": "medium", "reach": 4500, "feasibility": 80}]},
    {"id": "sangli", "name": "Sangli", "region": "Western Maharashtra", "grid": [2, 8], "population": {"total": 2822143, "youth": 705536}, "indicators": {"education": {"score": 38, "dropout": 16.5, "transition": 76.2, "accessIndex": 68}, "social": {"score": 32, "childMarriage": 14.2, "childLabour": 3.8, "adolescentVulnerability": 28}, "employment": {"score": 45, "unemploymentRate": 9.5, "jobDemandIndex": 45}, "skills": {"score": 48, "demandSupplyGap": 44, "curriculumAlignment": 56}, "livelihood": {"score": 38, "migrationRate": 11.5, "agriDependence": 45}, "health": {"score": 28, "youthHealthIndex": 72}}, "evidenceChain": [{"factor": "Turmeric & grape economy with processing potential", "arrow": True}, {"factor": "Cooperative movement provides safety net", "arrow": True}, {"factor": "Youth prefer white-collar jobs over agri-enterprise", "arrow": True}, {"factor": "Aspiration-opportunity mismatch", "arrow": False}], "interventions": [{"domain": "Skills", "action": "Agri-business & export-quality processing training", "priority": 76, "impact": "high", "reach": 5200, "feasibility": 82}, {"domain": "Employment", "action": "Start-up incubation for agri-entrepreneurs", "priority": 72, "impact": "medium", "reach": 3200, "feasibility": 75}]},
    {"id": "solapur", "name": "Solapur", "region": "Western Maharashtra", "grid": [3, 7], "population": {"total": 4317756, "youth": 1079439}, "indicators": {"education": {"score": 55, "dropout": 26.2, "transition": 65.8, "accessIndex": 52}, "social": {"score": 52, "childMarriage": 22.8, "childLabour": 6.5, "adolescentVulnerability": 45}, "employment": {"score": 50, "unemploymentRate": 10.8, "jobDemandIndex": 42}, "skills": {"score": 55, "demandSupplyGap": 52, "curriculumAlignment": 48}, "livelihood": {"score": 55, "migrationRate": 15.8, "agriDependence": 52}, "health": {"score": 42, "youthHealthIndex": 58}}, "evidenceChain": [{"factor": "Textile (powerloom) cluster — traditional industry", "arrow": True}, {"factor": "Industry stagnation threatens existing jobs", "arrow": True}, {"factor": "Need to modernise skills for textile-tech", "arrow": True}, {"factor": "Drought-prone southern talukas have high distress", "arrow": False}], "interventions": [{"domain": "Skills", "action": "Textile-tech modernisation training (CAD, smart looms)", "priority": 82, "impact": "high", "reach": 6500, "feasibility": 80}, {"domain": "Employment", "action": "Powerloom cluster apprenticeship programme", "priority": 78, "impact": "high", "reach": 5200, "feasibility": 82}, {"domain": "Education", "action": "Drought-taluka education retention programme", "priority": 72, "impact": "medium", "reach": 4800, "feasibility": 68}]},
    {"id": "kolhapur", "name": "Kolhapur", "region": "Western Maharashtra", "grid": [1, 8], "population": {"total": 3876001, "youth": 969000}, "indicators": {"education": {"score": 28, "dropout": 12.5, "transition": 84.2, "accessIndex": 78}, "social": {"score": 22, "childMarriage": 10.2, "childLabour": 2.5, "adolescentVulnerability": 18}, "employment": {"score": 35, "unemploymentRate": 7.5, "jobDemandIndex": 58}, "skills": {"score": 40, "demandSupplyGap": 36, "curriculumAlignment": 64}, "livelihood": {"score": 22, "migrationRate": 6.8, "agriDependence": 32}, "health": {"score": 22, "youthHealthIndex": 78}}, "evidenceChain": [{"factor": "Strong foundry & engineering MSME cluster", "arrow": True}, {"factor": "Cooperative dairy & sugar economy", "arrow": True}, {"factor": "Good education access & social indicators", "arrow": True}, {"factor": "Skills need upgrading for Industry 4.0", "arrow": False}], "interventions": [{"domain": "Skills", "action": "Industry 4.0 skill modules (robotics, IoT for foundries)", "priority": 82, "impact": "high", "reach": 7500, "feasibility": 88}, {"domain": "Employment", "action": "Foundry cluster technical apprenticeships", "priority": 78, "impact": "high", "reach": 5800, "feasibility": 90}]},
    {"id": "ahmednagar", "name": "Ahmednagar", "region": "Western Maharashtra", "grid": [3, 5], "population": {"total": 4543159, "youth": 1135790}, "indicators": {"education": {"score": 48, "dropout": 22.5, "transition": 70.2, "accessIndex": 58}, "social": {"score": 42, "childMarriage": 18.8, "childLabour": 5.2, "adolescentVulnerability": 35}, "employment": {"score": 45, "unemploymentRate": 9.5, "jobDemandIndex": 48}, "skills": {"score": 50, "demandSupplyGap": 46, "curriculumAlignment": 54}, "livelihood": {"score": 48, "migrationRate": 14.2, "agriDependence": 52}, "health": {"score": 35, "youthHealthIndex": 65}}, "evidenceChain": [{"factor": "Largest district — vast rural hinterland", "arrow": True}, {"factor": "Drought in east, prosperity in west (sugar belt)", "arrow": True}, {"factor": "Intra-district inequality drives internal migration", "arrow": True}, {"factor": "MIDC present but skill supply insufficient", "arrow": False}], "interventions": [{"domain": "Skills", "action": "MIDC-linked skill development in eastern talukas", "priority": 80, "impact": "high", "reach": 8500, "feasibility": 78}, {"domain": "Education", "action": "Eastern-taluka school quality equalisation", "priority": 76, "impact": "high", "reach": 6200, "feasibility": 72}, {"domain": "Employment", "action": "Sugar-cooperative diversification employment", "priority": 72, "impact": "medium", "reach": 5500, "feasibility": 75}]},
    # -- Konkan --
    {"id": "mumbai", "name": "Mumbai", "region": "Konkan", "grid": [0, 5], "population": {"total": 12442373, "youth": 3110593}, "indicators": {"education": {"score": 22, "dropout": 10.2, "transition": 88.5, "accessIndex": 88}, "social": {"score": 25, "childMarriage": 8.5, "childLabour": 2.8, "adolescentVulnerability": 18}, "employment": {"score": 22, "unemploymentRate": 4.8, "jobDemandIndex": 95}, "skills": {"score": 30, "demandSupplyGap": 28, "curriculumAlignment": 72}, "livelihood": {"score": 10, "migrationRate": 2.5, "agriDependence": 2}, "health": {"score": 20, "youthHealthIndex": 80}}, "evidenceChain": [{"factor": "India's financial capital — massive job market", "arrow": True}, {"factor": "World-class institutions but extreme cost", "arrow": True}, {"factor": "Slum youth (40%+ population) face systemic exclusion", "arrow": True}, {"factor": "Skills gap in fintech, data, digital marketing", "arrow": False}], "interventions": [{"domain": "Skills", "action": "Slum-youth digital skills bootcamp (fintech, data)", "priority": 90, "impact": "high", "reach": 25000, "feasibility": 88}, {"domain": "Employment", "action": "Corporate CSR apprenticeship mandate linkage", "priority": 86, "impact": "high", "reach": 18000, "feasibility": 82}, {"domain": "Education", "action": "Community college expansion in M-East ward", "priority": 78, "impact": "medium", "reach": 12000, "feasibility": 70}]},
    {"id": "thane", "name": "Thane", "region": "Konkan", "grid": [0, 4], "population": {"total": 11060148, "youth": 2765037}, "indicators": {"education": {"score": 30, "dropout": 14.2, "transition": 82.5, "accessIndex": 78}, "social": {"score": 32, "childMarriage": 12.8, "childLabour": 3.5, "adolescentVulnerability": 25}, "employment": {"score": 30, "unemploymentRate": 6.2, "jobDemandIndex": 78}, "skills": {"score": 35, "demandSupplyGap": 32, "curriculumAlignment": 68}, "livelihood": {"score": 18, "migrationRate": 5.8, "agriDependence": 15}, "health": {"score": 22, "youthHealthIndex": 78}}, "evidenceChain": [{"factor": "Industrial corridor (MIDC) + IT parks", "arrow": True}, {"factor": "Large tribal population in eastern talukas", "arrow": True}, {"factor": "Sharp urban-tribal divide in outcomes", "arrow": True}, {"factor": "Tribal youth face access barriers to quality skilling", "arrow": False}], "interventions": [{"domain": "Skills", "action": "Tribal-youth-to-industry bridging programme", "priority": 82, "impact": "high", "reach": 8500, "feasibility": 78}, {"domain": "Employment", "action": "MIDC apprenticeship expansion", "priority": 80, "impact": "high", "reach": 10000, "feasibility": 85}, {"domain": "Education", "action": "Tribal-taluka residential school quality upgrade", "priority": 75, "impact": "medium", "reach": 6200, "feasibility": 72}]},
    {"id": "palghar", "name": "Palghar", "region": "Konkan", "grid": [0, 3], "population": {"total": 2990116, "youth": 747529}, "indicators": {"education": {"score": 65, "dropout": 32.5, "transition": 58.2, "accessIndex": 42}, "social": {"score": 68, "childMarriage": 30.5, "childLabour": 9.8, "adolescentVulnerability": 60}, "employment": {"score": 55, "unemploymentRate": 12.5, "jobDemandIndex": 38}, "skills": {"score": 62, "demandSupplyGap": 58, "curriculumAlignment": 42}, "livelihood": {"score": 60, "migrationRate": 18.5, "agriDependence": 55}, "health": {"score": 65, "youthHealthIndex": 35}}, "evidenceChain": [{"factor": "Tribal-majority district adjacent to Mumbai", "arrow": True}, {"factor": "Severe malnutrition & health indicators", "arrow": True}, {"factor": "Proximity to Mumbai doesn't translate to opportunity", "arrow": True}, {"factor": "Child marriage & dropout among highest in Konkan", "arrow": False}], "interventions": [{"domain": "Health", "action": "Adolescent nutrition & health programme", "priority": 90, "impact": "high", "reach": 8500, "feasibility": 72}, {"domain": "Education", "action": "Tribal ashramshala quality transformation", "priority": 88, "impact": "high", "reach": 6200, "feasibility": 68}, {"domain": "Girls", "action": "Girls' retention & anti-child-marriage drive", "priority": 85, "impact": "high", "reach": 4800, "feasibility": 70}, {"domain": "Skills", "action": "Mumbai-linked placement-guarantee training", "priority": 80, "impact": "high", "reach": 5500, "feasibility": 78}]},
    {"id": "raigad", "name": "Raigad", "region": "Konkan", "grid": [1, 6], "population": {"total": 2634200, "youth": 658550}, "indicators": {"education": {"score": 38, "dropout": 16.8, "transition": 76.5, "accessIndex": 68}, "social": {"score": 35, "childMarriage": 14.5, "childLabour": 3.8, "adolescentVulnerability": 28}, "employment": {"score": 35, "unemploymentRate": 7.8, "jobDemandIndex": 58}, "skills": {"score": 42, "demandSupplyGap": 38, "curriculumAlignment": 62}, "livelihood": {"score": 28, "migrationRate": 8.5, "agriDependence": 30}, "health": {"score": 30, "youthHealthIndex": 70}}, "evidenceChain": [{"factor": "JNPT & industrial belt provides employment", "arrow": True}, {"factor": "Coastal tourism economy growing", "arrow": True}, {"factor": "Skills gap in logistics, port operations, hospitality", "arrow": True}, {"factor": "Hilly interior talukas face access challenges", "arrow": False}], "interventions": [{"domain": "Skills", "action": "Logistics & port-operations certification", "priority": 80, "impact": "high", "reach": 5200, "feasibility": 85}, {"domain": "Employment", "action": "JNPT apprenticeship corridor", "priority": 78, "impact": "high", "reach": 4500, "feasibility": 88}]},
    {"id": "ratnagiri", "name": "Ratnagiri", "region": "Konkan", "grid": [1, 7], "population": {"total": 1615069, "youth": 403767}, "indicators": {"education": {"score": 35, "dropout": 15.8, "transition": 78.2, "accessIndex": 70}, "social": {"score": 28, "childMarriage": 11.5, "childLabour": 3.2, "adolescentVulnerability": 22}, "employment": {"score": 55, "unemploymentRate": 11.2, "jobDemandIndex": 32}, "skills": {"score": 52, "demandSupplyGap": 48, "curriculumAlignment": 52}, "livelihood": {"score": 48, "migrationRate": 22.5, "agriDependence": 45}, "health": {"score": 25, "youthHealthIndex": 75}}, "evidenceChain": [{"factor": "Good education indicators but shrinking local economy", "arrow": True}, {"factor": "Mango & cashew economy with limited processing", "arrow": True}, {"factor": "Massive youth out-migration to Mumbai", "arrow": True}, {"factor": "Aging population left behind", "arrow": False}], "interventions": [{"domain": "Skills", "action": "Food-processing & cold-chain management training", "priority": 78, "impact": "high", "reach": 3500, "feasibility": 80}, {"domain": "Employment", "action": "Coastal tourism & homestay enterprise", "priority": 74, "impact": "medium", "reach": 2800, "feasibility": 78}, {"domain": "Livelihood", "action": "Konkan mango/cashew value-chain enterprise", "priority": 72, "impact": "medium", "reach": 3200, "feasibility": 75}]},
    {"id": "sindhudurg", "name": "Sindhudurg", "region": "Konkan", "grid": [1, 9], "population": {"total": 849651, "youth": 212413}, "indicators": {"education": {"score": 25, "dropout": 10.8, "transition": 85.2, "accessIndex": 82}, "social": {"score": 18, "childMarriage": 7.5, "childLabour": 1.8, "adolescentVulnerability": 14}, "employment": {"score": 58, "unemploymentRate": 12.5, "jobDemandIndex": 25}, "skills": {"score": 50, "demandSupplyGap": 45, "curriculumAlignment": 55}, "livelihood": {"score": 52, "migrationRate": 28.5, "agriDependence": 42}, "health": {"score": 18, "youthHealthIndex": 82}}, "evidenceChain": [{"factor": "Best social & education indicators in state", "arrow": True}, {"factor": "But highest out-migration rate — economy can't retain youth", "arrow": True}, {"factor": "Tourism potential massively under-leveraged", "arrow": True}, {"factor": "Population decline threatens long-term viability", "arrow": False}], "interventions": [{"domain": "Employment", "action": "Eco-tourism & hospitality enterprise incubation", "priority": 82, "impact": "high", "reach": 2500, "feasibility": 80}, {"domain": "Skills", "action": "Marine fisheries & aquaculture modern training", "priority": 78, "impact": "high", "reach": 2200, "feasibility": 76}, {"domain": "Livelihood", "action": "Cashew & kokum processing enterprises", "priority": 74, "impact": "medium", "reach": 1800, "feasibility": 78}]},
    {"id": "mumbaisuburban", "name": "Mumbai Suburban", "region": "Konkan", "grid": [0, 6], "population": {"total": 9356962, "youth": 2339241}, "indicators": {"education": {"score": 20, "dropout": 9.5, "transition": 90.2, "accessIndex": 90}, "social": {"score": 22, "childMarriage": 7.2, "childLabour": 2.2, "adolescentVulnerability": 15}, "employment": {"score": 20, "unemploymentRate": 4.5, "jobDemandIndex": 92}, "skills": {"score": 28, "demandSupplyGap": 25, "curriculumAlignment": 75}, "livelihood": {"score": 8, "migrationRate": 2.2, "agriDependence": 1}, "health": {"score": 18, "youthHealthIndex": 82}}, "evidenceChain": [{"factor": "Highest economic density in India", "arrow": True}, {"factor": "Film, media, finance & tech hub", "arrow": True}, {"factor": "Extreme cost of living as barrier", "arrow": True}, {"factor": "Digital skills gap in transition economy", "arrow": False}], "interventions": [{"domain": "Skills", "action": "Digital media & content creation bootcamp", "priority": 85, "impact": "high", "reach": 20000, "feasibility": 90}, {"domain": "Employment", "action": "Gig economy skill & rights training", "priority": 80, "impact": "high", "reach": 15000, "feasibility": 85}]},
    {"id": "navi_mumbai", "name": "Navi Mumbai (Raigad Urban)", "region": "Konkan", "grid": [1, 5], "population": {"total": 1120547, "youth": 280137}, "indicators": {"education": {"score": 22, "dropout": 10.5, "transition": 88.2, "accessIndex": 85}, "social": {"score": 20, "childMarriage": 6.8, "childLabour": 1.5, "adolescentVulnerability": 14}, "employment": {"score": 25, "unemploymentRate": 5.5, "jobDemandIndex": 82}, "skills": {"score": 32, "demandSupplyGap": 28, "curriculumAlignment": 72}, "livelihood": {"score": 10, "migrationRate": 3.2, "agriDependence": 5}, "health": {"score": 18, "youthHealthIndex": 82}}, "evidenceChain": [{"factor": "Planned city with strong IT/ITES presence", "arrow": True}, {"factor": "CIDCO industrial zones provide employment", "arrow": True}, {"factor": "Skills gap in cloud computing & data analytics", "arrow": True}, {"factor": "New airport expected to create logistics jobs", "arrow": False}], "interventions": [{"domain": "Skills", "action": "Airport & logistics sector pre-employment training", "priority": 85, "impact": "high", "reach": 5500, "feasibility": 90}, {"domain": "Employment", "action": "IT Park apprenticeship expansion", "priority": 82, "impact": "high", "reach": 4800, "feasibility": 88}]},
    # -- North Maharashtra --
    {"id": "nashik", "name": "Nashik", "region": "North Maharashtra", "grid": [2, 4], "population": {"total": 6107187, "youth": 1526797}, "indicators": {"education": {"score": 40, "dropout": 18.2, "transition": 74.5, "accessIndex": 68}, "social": {"score": 38, "childMarriage": 16.5, "childLabour": 4.5, "adolescentVulnerability": 32}, "employment": {"score": 38, "unemploymentRate": 8.2, "jobDemandIndex": 62}, "skills": {"score": 42, "demandSupplyGap": 38, "curriculumAlignment": 62}, "livelihood": {"score": 35, "migrationRate": 10.5, "agriDependence": 38}, "health": {"score": 30, "youthHealthIndex": 70}}, "evidenceChain": [{"factor": "Wine capital + defense manufacturing cluster", "arrow": True}, {"factor": "Tribal talukas in east have very different reality", "arrow": True}, {"factor": "Kumbh Mela pilgrimage economy (periodic)", "arrow": True}, {"factor": "Dual economy: modern west vs tribal east", "arrow": False}], "interventions": [{"domain": "Skills", "action": "Defense & precision manufacturing skill modules", "priority": 84, "impact": "high", "reach": 8500, "feasibility": 85}, {"domain": "Education", "action": "Tribal taluka education quality programme", "priority": 80, "impact": "high", "reach": 6500, "feasibility": 72}, {"domain": "Employment", "action": "Grape & wine industry skill certification", "priority": 74, "impact": "medium", "reach": 4200, "feasibility": 82}]},
    {"id": "dhule", "name": "Dhule", "region": "North Maharashtra", "grid": [2, 3], "population": {"total": 2050862, "youth": 512716}, "indicators": {"education": {"score": 68, "dropout": 35.2, "transition": 55.8, "accessIndex": 40}, "social": {"score": 65, "childMarriage": 30.8, "childLabour": 9.5, "adolescentVulnerability": 58}, "employment": {"score": 60, "unemploymentRate": 14.2, "jobDemandIndex": 28}, "skills": {"score": 65, "demandSupplyGap": 62, "curriculumAlignment": 38}, "livelihood": {"score": 68, "migrationRate": 22.5, "agriDependence": 65}, "health": {"score": 55, "youthHealthIndex": 45}}, "evidenceChain": [{"factor": "Large tribal population (Bhil, Pawra communities)", "arrow": True}, {"factor": "Low education access in tribal talukas", "arrow": True}, {"factor": "High child marriage & adolescent vulnerability", "arrow": True}, {"factor": "Highway corridor (NH3) potential under-utilised", "arrow": False}], "interventions": [{"domain": "Education", "action": "Tribal residential school expansion & quality", "priority": 88, "impact": "high", "reach": 5500, "feasibility": 65}, {"domain": "Girls", "action": "Tribal girls' secondary education programme", "priority": 85, "impact": "high", "reach": 4200, "feasibility": 68}, {"domain": "Skills", "action": "Highway-corridor logistics & driving training", "priority": 78, "impact": "medium", "reach": 3800, "feasibility": 80}]},
    {"id": "nandurbar", "name": "Nandurbar", "region": "North Maharashtra", "grid": [1, 2], "population": {"total": 1648295, "youth": 412074}, "indicators": {"education": {"score": 80, "dropout": 44.2, "transition": 44.5, "accessIndex": 30}, "social": {"score": 78, "childMarriage": 38.2, "childLabour": 14.8, "adolescentVulnerability": 70}, "employment": {"score": 72, "unemploymentRate": 18.2, "jobDemandIndex": 18}, "skills": {"score": 78, "demandSupplyGap": 75, "curriculumAlignment": 25}, "livelihood": {"score": 82, "migrationRate": 35.5, "agriDependence": 80}, "health": {"score": 75, "youthHealthIndex": 25}}, "evidenceChain": [{"factor": "69% tribal population — highest in state", "arrow": True}, {"factor": "Extreme malnutrition (child wasting >30%)", "arrow": True}, {"factor": "Minimal institutional infrastructure", "arrow": True}, {"factor": "Mass seasonal migration to Gujarat farms", "arrow": True}, {"factor": "Second-worst human development index in Maharashtra", "arrow": False}], "interventions": [{"domain": "Health", "action": "Adolescent nutrition mission (POSHAN Abhiyaan plus)", "priority": 95, "impact": "high", "reach": 8500, "feasibility": 58}, {"domain": "Education", "action": "Residential bridge school + scholarship for tribal youth", "priority": 92, "impact": "high", "reach": 6200, "feasibility": 62}, {"domain": "Girls", "action": "Girls' empowerment hub — education, health, skills", "priority": 88, "impact": "high", "reach": 4800, "feasibility": 60}, {"domain": "Livelihood", "action": "Forest-rights & NTFP enterprise development", "priority": 82, "impact": "high", "reach": 3500, "feasibility": 55}]},
    {"id": "jalgaon", "name": "Jalgaon", "region": "North Maharashtra", "grid": [3, 3], "population": {"total": 4229917, "youth": 1057479}, "indicators": {"education": {"score": 48, "dropout": 22.8, "transition": 70.5, "accessIndex": 58}, "social": {"score": 42, "childMarriage": 18.5, "childLabour": 5.5, "adolescentVulnerability": 36}, "employment": {"score": 45, "unemploymentRate": 9.8, "jobDemandIndex": 48}, "skills": {"score": 50, "demandSupplyGap": 46, "curriculumAlignment": 54}, "livelihood": {"score": 45, "migrationRate": 12.8, "agriDependence": 50}, "health": {"score": 35, "youthHealthIndex": 65}}, "evidenceChain": [{"factor": "Banana capital — strong agri-commerce", "arrow": True}, {"factor": "Gold & textile MSME cluster (Jalgaon jewellery)", "arrow": True}, {"factor": "Education access moderate but quality gaps", "arrow": True}, {"factor": "MSME sector needs formally skilled workforce", "arrow": False}], "interventions": [{"domain": "Skills", "action": "Goldsmith & jewellery design certification (CAD)", "priority": 80, "impact": "high", "reach": 5500, "feasibility": 85}, {"domain": "Skills", "action": "Banana processing & export-quality packaging", "priority": 76, "impact": "high", "reach": 4200, "feasibility": 82}, {"domain": "Employment", "action": "MSME apprenticeship programme", "priority": 74, "impact": "medium", "reach": 6200, "feasibility": 80}]},
]


async def seed():
    client = AsyncIOMotorClient(settings.mongodb_uri, tlsCAFile=certifi.where())
    db = client[settings.database_name]

    await db.districts.create_index("id", unique=True)

    existing = await db.districts.count_documents({})
    if existing > 0:
        print(f"Dropping {existing} existing districts...")
        await db.districts.delete_many({})

    result = await db.districts.insert_many(DISTRICTS)
    print(f"Seeded {len(result.inserted_ids)} districts into MongoDB")
    print(f"  Database: {settings.database_name}")
    print(f"  Collection: districts")

    sample = await db.districts.find_one({"id": "beed"}, {"_id": 0, "name": 1, "region": 1})
    print(f"  Verification: {sample}")

    client.close()


if __name__ == "__main__":
    asyncio.run(seed())
